# Generated by Django 4.1.1 on 2022-10-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datanet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='default', max_length=64),
            preserve_default=False,
        ),
    ]
